KingsConsulting/Entities/ServiceType.cs
using System;
using System.Collections.Generic;

namespace KingsConsulting.Entities;

public partial class ServiceType
{
    public int ServiceTypeId { get; set; }

    public string ServiceName { get; set; } = null!;

    public virtual ICollection<OrderContent> OrderContents { get; } = new List<OrderContent>();
}

KingsConsulting/Models/ServiceType.cs
using System;
using System.Collections.Generic;

namespace KingsConsulting.Models;

public partial class ServiceType
{
    public int ServiceTypeId { get; set; }

    public string ServiceName { get; set; } = null!;

    public virtual ICollection<OrderContent> OrderContents { get; } = new List<OrderContent>();
}

KingsConsulting/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KingsConsulting.Pages

{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

KingsConsulting/Pages/Account.cshtml.cs
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using KingsConsulting.Model;

namespace KingsConsulting.Pages
{
    public class AccountModel : PageModel
    {
        public bool IsUserActive { get; set; } = false;

        public string Email { get; set; } = string.Empty;

        public string FirstName { get; set; } = string.Empty;

        public string LastName { get; set; } = string.Empty;

        public string PhoneNumber { get; set; } = string.Empty;

        /// <summary>
        /// Formats the phone number to a standard format.
        /// </summary>
        public string FormatPhoneNumber(string phone)
        {
            Regex regex = new Regex(@"[^\d]");
            phone = regex.Replace(phone, "");
            string format = "###-###-####";
            phone = Convert.ToInt64(phone).ToString(format);
            return phone;
        }

        public void OnGet()
        {
            // Retrieve the user's information from session.
            Email = HttpContext.Session.GetString("Email");
            FirstName = HttpContext.Session.GetString("FirstName");
            LastName = HttpContext.Session.GetString("LastName");
            PhoneNumber = HttpContext.Session.GetString("PhoneNumber");

            // Determine if the user is active.
            if (Email != null && Email != "")
            {
                IsUserActive = true;
            }
        }

        public IActionResult OnPostSubmit()
        {
            // Clear the user's session.
            HttpContext.Session.Clear();

            // Setup a message to display to the user.
            TempData[Constants.AlertSuccess] = Email == string.Empty ? null : "Logout Successful!";

            return Redirect("/Login");
        }
    }
}

KingsConsulting/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using KingsConsulting.Model;

namespace KingsConsulting.Pages
{
    public class ContactModel : PageModel
    {

        [BindProperty]
        [Display(Name = "Name")]
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; } = string.Empty;

        [BindProperty]
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Please enter your email address.")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address.")]
        public string Email { get; set; } = string.Empty;

        [BindProperty]
        [Required(ErrorMessage = "Please select an option.")]
        public string CategoryOption { get; set; } = "1";

        [BindProperty]
        [Required(ErrorMessage = "Please select an option.")]
        public string BudgetOption { get; set; } = "1";

        [BindProperty]
        [Display(Name = "Message")]
        [Required(ErrorMessage = "Please enter a message.")]
        public string Message { get; set; } = string.Empty;

        public void OnGet()
        {
        }

        /// <summary>
        /// Clears the form and model.
        /// </summary>
        public IActionResult OnPostCancel()
        {
            ModelState.Clear();
            Name = string.Empty;
            Email = string.Empty;
            Message = string.Empty;
            CategoryOption = "1";
            BudgetOption = "1";

            return Page();
        }

        public IActionResult OnPostSubmit()
        {
            // Validate the model.
            if (ModelState.IsValid)
            {
                return Page();
            }

            TempData[Constants.AlertSuccess] = "Thank you for your message. We will get back to you shortly.";
            return Page();
        }
    }
}

KingsConsulting/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace KingsConsulting.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

KingsConsulting/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KingsConsulting.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public string Message { get; set; } = string.Empty;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            // Retrieve the user's information from session.
            var userId = HttpContext.Session.GetString("UserId");
            var email = HttpContext.Session.GetString("Email");
            var firstName = HttpContext.Session.GetString("FirstName");
            var lastName = HttpContext.Session.GetString("LastName");

            // Determine if the user is active.
            if (email != null && email != "")
            {
                Message = "Welcome " + firstName + ", to <br/>";
            }
        }
    }
}

KingsConsulting/Pages/Login.cshtml.cs
using System.ComponentModel.DataAnnotations;
using KingsConsulting.Entities;
using KingsConsulting.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using System.Data;
using System.Text.Json;

namespace KingsConsulting.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Please enter your email address.")]
        public string Email { get; set; } = string.Empty;

        [BindProperty]
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please enter your password")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password length must be at least 6 characters.")]
        public string Password { get; set; } = string.Empty;

        public string Message { get; set; } = string.Empty;

        public UserInfo MyUserInfo { get; set; }

        private readonly IConfiguration configuration;

        public LoginModel(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public void OnGet()
        {
        }

        /// <summary>
        /// Clears the form and model.
        /// </summary>
        public IActionResult OnPostCancel()
        {
            ModelState.Clear();
            Email = string.Empty;
            Password = string.Empty;

            return Page();
        }

        public IActionResult OnPostSubmit()
        {
            // check if model state is valid
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // establish connection to database
            var strConn = configuration.GetConnectionString("DefaultConnection");

            using (SqlConnection sqlConn = new(strConn))
            {
                // open connection and select stored procedure
                SqlDataAdapter sqlDataValidator = new SqlDataAdapter("spValidateUser", sqlConn);
                sqlDataValidator.SelectCommand.CommandType = CommandType.StoredProcedure;

                // add parameters to stored procedure
                sqlDataValidator.SelectCommand.Parameters.AddWithValue("@email", Email);
                sqlDataValidator.SelectCommand.Parameters.AddWithValue("@passcode", Password);

                try
                {
                    DataSet dsUserRecord = new DataSet();

                    // fill dataset with results from stored procedure
                    sqlDataValidator.Fill(dsUserRecord);

                    // check if dataset is empty
                    if (dsUserRecord.Tables[0].Rows.Count == 0)
                    {
                        Message = "Invalid login, please try again";
                        return Page();
                    }

                    // get user information from dataset
                    MyUserInfo = new UserInfo();
                    MyUserInfo.UserId = Convert.ToInt32(dsUserRecord.Tables[0].Rows[0]["userId"]);
                    MyUserInfo.Email = dsUserRecord.Tables[0].Rows[0]["email"].ToString();
                    MyUserInfo.FirstName = dsUserRecord.Tables[0].Rows[0]["firstName"].ToString();
                    MyUserInfo.LastName = dsUserRecord.Tables[0].Rows[0]["lastName"].ToString();
                    MyUserInfo.PhoneNumber = dsUserRecord.Tables[0].Rows[0]["phoneNumber"].ToString();

                    // set session variables
                    HttpContext.Session.SetString("UserId", MyUserInfo.UserId.ToString());
                    HttpContext.Session.SetString("Email", MyUserInfo.Email!);
                    HttpContext.Session.SetString("FirstName", MyUserInfo.FirstName!);
                    HttpContext.Session.SetString("LastName", MyUserInfo.LastName!);
                    HttpContext.Session.SetString("PhoneNumber", MyUserInfo.PhoneNumber!);

                    // reset model state
                    Email = string.Empty;
                    Password = string.Empty;
                    ModelState.Clear();

                    TempData[Constants.AlertSuccess] = "Login Successful!";

                    return Redirect("/Index");

                }
                catch(Exception e)
                {
                    Message = e.Message;
                    TempData[Constants.AlertWarning] = "Unable to login.";
                    return Page();
                }
            };
        }
    }
}

KingsConsulting/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KingsConsulting.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

KingsConsulting/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using KingsConsulting.Entities;
using KingsConsulting.Model;
using Microsoft.Data.SqlClient;
using System.Data;

namespace KingsConsulting.Pages
{
    public class RegisterModel : PageModel
    {
        [BindProperty]
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please enter your first name")]
        public string FirstName { get; set; } = string.Empty;

        [BindProperty]
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please enter your last name")]
        public string LastName { get; set; } = string.Empty;

        [BindProperty]
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Please enter your email address.")]
        public string Email { get; set; } = string.Empty;

        [BindProperty]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Please enter your phone number.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string PhoneNumber { get; set; } = string.Empty;

        [BindProperty]
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please enter your password")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password length must be at least 6 characters.")]
        public string Password { get; set; } = string.Empty;

        [BindProperty]
        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "Please confirm your password")]
        [Compare("Password", ErrorMessage = "Passwords do not match.")]
        public string ConfirmPassword { get; set; } = string.Empty;

        public string StatusMessage { get; set; } = string.Empty;

        public UserInfo NewUserInfo { get; set; }

        private readonly IConfiguration configuration;

        public RegisterModel(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public void OnGet()
        {
        }

        /// <summary>
        /// Clears the form and model.
        /// </summary>
        public IActionResult OnPostCancel()
        {
            ModelState.Clear();
            FirstName = string.Empty;
            LastName = string.Empty;
            Email = string.Empty;
            Password = string.Empty;
            ConfirmPassword = string.Empty;
            PhoneNumber = string.Empty;
            StatusMessage = string.Empty;

            return Page();
        }

        public IActionResult OnPostSubmit()
        {
            // check if model state is valid
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // establish connection to database
            var strConn = configuration.GetConnectionString("DefaultConnection");

            using (SqlConnection sqlConn = new(strConn))
            {
                // select stored procedure
                SqlDataAdapter sqlDataValidator = new SqlDataAdapter("spCreateUser", sqlConn);
                sqlDataValidator.SelectCommand.CommandType = CommandType.StoredProcedure;

                // add parameters
                sqlDataValidator.SelectCommand.Parameters.AddWithValue("@firstName", FirstName);
                sqlDataValidator.SelectCommand.Parameters.AddWithValue("@lastName", LastName);
                sqlDataValidator.SelectCommand.Parameters.AddWithValue("@email", Email);
                sqlDataValidator.SelectCommand.Parameters.AddWithValue("@passcode", Password);
                sqlDataValidator.SelectCommand.Parameters.AddWithValue("@phone", PhoneNumber);

                try
                {
                    DataSet dsUserRecord = new DataSet();

                    // open connection and fill dataset
                    sqlDataValidator.Fill(dsUserRecord);

                    // check if dataset is empty
                    if (dsUserRecord.Tables[0].Rows.Count == 0)
                    {
                        StatusMessage = "Invalid registration, please try again";
                        return Page();
                    }

                    // clear form and model
                    FirstName = string.Empty;
                    LastName = string.Empty;
                    Email = string.Empty;
                    PhoneNumber = string.Empty;
                    Password = string.Empty;
                    ConfirmPassword = string.Empty;
                    ModelState.Clear();

                    TempData[Constants.AlertSuccess] = "<strong>Account Creation Successful!</strong> Please login now!";

                    return Redirect("/Login");

                }
                catch (Exception e)
                {
                    StatusMessage = e.Message;
                    TempData[Constants.AlertWarning] = "Unable to create account.";
                    return Page();
                }
            };
        }

    }
}

KingsConsulting/Pages/Services.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KingsConsulting.Pages
{
    public class ServicesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

KingsConsulting/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}

<div class="row justify-content-center">
    @* Header *@
    <div class="display-5 animate-fade mt-5 line-zero">About Us</div>
    <div class="row row-cols-1 row-cols-md-2 g-5 align-items-center mt-1">
        @* About Image *@
        <div class="col justify-content-center animate-slide-left">
            <img src="../images/about.jpg" class="rounded img-fluid mx-auto" />
        </div>
        @* About Text *@
        <div class="col animate-slide-right">
            <div class="row p-3">
                <div class="col">
                    <h2 class="display-6">Who We Are</h2>
                    <p>
                        We are a team of web developers, mobile developers, and experienced consultants who are passionate about helping businesses and individuals realize their vision and bring their ideas to life.
                    </p>
                </div>
            </div>
            <div class="row p-3">
                <a class="link" href="/Services">Check out Services!</a>
            </div>
        </div>
    </div>
    @* Video Section *@
    <h2 class="display-6 mb-3 animate-fade mt-5 animate-fade delay-1">Our Mission</h2>
    <div class="row ratio ratio-1x1 video-width-max m-3 animate-fade delay-2">
        <iframe src="https://www.youtube.com/embed/yeiYJ57DrH4" frameborder="0" allowfullscreen></iframe>
    </div>
</div>

KingsConsulting/Pages/Account.cshtml
@page
@model KingsConsulting.Pages.AccountModel
@{
}

<form method="post">
    <div class="row align-items-center">
        <div class="col gap-3">

            @* Logic to check if user is logged in *@

            @if (Model.IsUserActive)
            {
                @* Display user information *@
                <div class="display-5 mb-5 animate-fade">My Account</div>
                <div class="account-row gap-2 mb-2 animate-slide-left delay-1">
                    <h6 class=" min-width">Email:</h6>
                    <div>@Model.Email</div>
                </div>
                <div class="account-row gap-2 mb-2 animate-slide-left delay-2">
                    <h6 class="min-width">First Name:</h6>
                    <div>@Model.FirstName</div>
                </div>
                <div class="account-row gap-2 mb-2 animate-slide-left delay-3">
                    <h6 class="min-width">Last Name:</h6>
                    <div>@Model.LastName</div>
                </div>
                <div class="account-row gap-2 mb-2 animate-slide-left delay-4">
                    <h6 class="min-width">Phone Number:</h6>
                    <div>@Model.FormatPhoneNumber(Model.PhoneNumber)</div>
                </div>
                <input class="btn btn-primary animate-up delay-5" type="submit" asp-page-handler="Submit" value="LOGOUT" />
            }
            else
            {
                @* Button to return to login form *@
                <div class="display-5 mb-5">No Active User Logged In</div>
                <a asp-page="/Login">Please Login Here</a>
            }
        </div>
    </div>
</form>

KingsConsulting/Pages/Contact.cshtml
@page
@model KingsConsulting.Pages.ContactModel
@{
}

<form method="post">
    <div class="row row-cols-1 row-cols-md-2 g-3 mt-5 align-items-center">
        @* Header *@
        <div class="col col-md-12">
            <div class="display-5 animate-fade">
                Questions? Get in touch
            </div>
        </div>
        @* Name *@
        <div class="col col-md-6 animate-up delay-1">
            <label for="inputName" asp-for="Name" class=" col-form-label">Your name</label>
            <input type="text" id="inputName" class="form-control" aria-describedby="nameHelpInLine" asp-for="Name">
            <span class="form-text" asp-validation-for="Name"></span>
        </div>
        @* Email *@
        <div class="col col-md-6 animate-up delay-2">
            <label for="inputEmail" asp-for="Email" class=" col-form-label">Your email</label>
            <input type="email" id="inputEmail" class="form-control" aria-describedby="emailHelpInline" asp-for="Email">
            <span class="form-text" asp-validation-for="Email"></span>
        </div>
        @* Category *@
        <div class="col col-md-6 animate-up delay-3">
            <label for="selectCategory" asp-for="CategoryOption" class="col-form-label">What you are interested in</label>
            <select class="form-select" id="selectCategory" aria-label="Service selection" asp-for="CategoryOption">
                <option selected value="1">General Consulting</option>
                <option value="2">Web Development</option>
                <option value="3">Mobile Development</option>
            </select>
        </div>
        @* Budget *@
        <div class="col col-md-6 animate-up delay-4">
            <label for="selectBudget" asp-for="BudgetOption" class="col-form-label">Project budget</label>
            <select class="form-select" id="selectBudget" aria-label="Budget selection" asp-for="BudgetOption">
                <option selected value="1">Less than $50</option>
                <option value="2">$50 - $100</option>
                <option value="3">$100 - $500</option>
                <option value="3">$500 - $1000</option>
                <option value="3">Other</option>
            </select>
        </div>
        @* Message *@
        <div class="col col-md-12 animate-up delay-5">
            <label for="inputMessage" asp-for="Message" class=" col-form-label">Message</label>
            <textarea id="inputMessage" rows="3" class="form-control" aria-describedby="messageHelpInline" asp-for="Message"></textarea>
            <span class="form-text" asp-validation-for="Message"></span>
        </div>
        @* Submit *@
        <div class="col animate-up delay-6">
            <input class="btn btn-secondary" type="submit" asp-page-handler="Cancel" value="CANCEL" />
            <input class="btn btn-primary" type="submit" asp-page-handler="Submit" value="SEND" />
        </div>
    </div>
</form>

@* Add section scripts for client-side validation so that invalid data does not get sent to the server *@
@section Scripts {
    @{
        @* This references Javascript files needed for validation. Located in the shared folder*@
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

KingsConsulting/Pages/Index.cshtml
@page "/Index"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="row row-cols-1 mt-5">
    @* Header *@
    <h1 class="col text-center p-3 display-1 animate-fade">@Html.Raw(@Model.Message)<strong>King's Consulting</strong></h1>
    <h2 class="col text-center lead mb-5 animate-up delay-1">Realizing and Reimagining Digital Media</h2>
    @* Main content *@
    <p class="col text-center animate-up delay-2 mb-2">
        If you're an entrepreneur, business owner, or creative professional, we can help you realize your vision and bring your ideas to life. We specialize in web design, web development, and digital marketing.
        The digital world is constantly evolving, and we're here to help you keep up with the latest trends and technologies.
        We can help you re-imagine your digital media and bring your ideas to life with our consulting, web development, and mobile
        app development services.
        <br />
        Here are some options to get started:
    </p>
    @* Arrows *@
    <div class="row mb-3">
        <div class="col text-center animate-bounce delay-5">
            <span>
                <i class="fas fa-arrow-down fa-2x animate-arrow"></i>
            </span>
        </div>
        <div class="col text-center animate-bounce delay-7">
            <span>
                <i class="fas fa-arrow-down fa-2x animate-arrow"></i>
            </span>
        </div>
        <div class="col text-center animate-bounce delay-9">
            <span>
                <i class="fas fa-arrow-down fa-2x animate-arrow"></i>
            </span>
        </div>
    </div>
    @* Buttons *@
    <div class="row gap-2">
        <div class="col text-center animate-slide-left delay-3">
            <a asp-page="./About"><button class="btn btn-primary animate-fade delay-1">LEARN MORE</button></a>
        </div>
        <div class="col text-center animate-slide-right delay-3">
            <a asp-page="./Contact"><button class="btn btn-secondary animate-fade delay-1">CONTACT ME</button></a>
        </div>
    </div>
</div>

KingsConsulting/Pages/Login.cshtml
@page
@model KingsConsulting.Pages.LoginModel
@{
}

<form method="post">
    <div class="row row-cols-1 row-cols-md-2 g-3 align-items-center mt-5">
        @* Header *@
        <div class="col col-md-12">
            <div class="display-5 animate-fade">
                Hello Again!
            </div>
        </div>
        <div class="col col-md-12">
            <p class="lead animate-fade delay-1">
                Login to access our amazing services!
            </p>
        </div>
        @* Form *@
        @* Email *@
        <div class="col col-md-12 animate-up delay-2">
            <label for="inputEmail" asp-for="Email" class=" col-form-label">Your email</label>
            <input type="email" id="inputEmail" class="form-control" aria-describedby="emailHelpInline" asp-for="Email">
            <span class="form-text" asp-validation-for="Email"></span>
        </div>
        @* Password *@
        <div class="col col-md-12 animate-up delay-3">
            <label for="inputPassword" asp-for="Password" class="col-form-label">Your password</label>
            <input type="password" id="inputPassword" class="form-control" aria-describedby="passwordHelpInline" asp-for="Password">
            <span id="passwordHelpInline" class="form-text"asp-validation-for="Password"> </span>
        </div>
        @* Buttons *@
        <div class="col col-md-12 animate-up delay-4">
            <input class="btn btn-secondary" type="submit" asp-page-handler="Cancel" value="CANCEL" />
            <input class="btn btn-primary" type="submit" asp-page-handler="Submit" value="LOGIN" />
        </div>
        @* Message *@
        <div class="col col-md-12">
            <p class="lead">
                @Model.Message
            </p>
        </div>
        @* Register Btn *@
        <div class="col col-md-12 animate-fade delay-5">
            <span>Need an account? </span><a asp-page="/Register">Register here!</a>
        </div>
    </div>
</form>

@* Add section scripts for client-side validation so that invalid data does not get sent to the server *@
@section Scripts {
    @{
        @* This references Javascript files needed for validation. Located in the shared folder*@
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

KingsConsulting/Pages/Register.cshtml
@page
@model KingsConsulting.Pages.RegisterModel
@{
}

<form method="post">
    <div class="row row-cols-1 row-cols-md-2 g-3 align-items-center mt-5">
        @* Header *@
        <div class="col col-md-12">
            <div class="display-5 animate-fade">
                Welcome!
            </div>
        </div>
        <div class="col col-md-12">
            <p class="lead animate-fade delay-1">
                Register for a quicker and smoother experience!
            </p>
        </div>
        @* First Name *@
        <div class="col col-md-12 animate-up delay-2">
            <label for="inputfName" asp-for="FirstName" class=" col-form-label">First name</label>
            <input type="text" id="inputfName" class="form-control" aria-describedby="fNameHelpInLine" asp-for="FirstName">
            <span class="form-text" asp-validation-for="FirstName"></span>
        </div>
        @* Last Name *@
        <div class="col col-md-12 animate-up delay-3">
            <label for="inputlName" asp-for="LastName" class=" col-form-label">Last name</label>
            <input type="text" id="inputlName" class="form-control" aria-describedby="fNameHelpInLine" asp-for="LastName">
            <span class="form-text" asp-validation-for="LastName"></span>
        </div>
        @* Phone *@
        <div class="col col-md-12 animate-up delay-4">
            <label for="inputPhone" asp-for="PhoneNumber" class=" col-form-label">Your phone number</label>
            <input type="tel" id="inputPhone" class="form-control" aria-describedby="phoneHelpInline" asp-for="PhoneNumber">
            <span class="form-text" asp-validation-for="PhoneNumber"></span>
        </div>
        @* Email *@
        <div class="col col-md-12 animate-up delay-5">
            <label for="inputEmail" asp-for="Email" class=" col-form-label">Your email</label>
            <input type="email" id="inputEmail" class="form-control" aria-describedby="emailHelpInline" asp-for="Email">
            <span class="form-text" asp-validation-for="Email"></span>
        </div>
        @* Password *@
        <div class="col col-md-12 animate-up delay-6">
            <label for="inputPassword" asp-for="Password" class="col-form-label">Your password</label>
            <input type="password" id="inputPassword" class="form-control" aria-describedby="passwordHelpInline" asp-for="Password">
            <span id="passwordHelpInline" class="form-text" asp-validation-for="Password"> </span>
        </div>
        @* Confirm Password *@
        <div class="col col-md-12 animate-up delay-7">
            <label for="inputConfirmPassword" asp-for="ConfirmPassword" class="col-form-label">Confirm your password</label>
            <input type="password" id="inputConfirmPassword" class="form-control" aria-describedby="confirmPasswordHelpInline" asp-for="ConfirmPassword">
            <span id="confirmPasswordHelpInline" class="form-text" asp-validation-for="ConfirmPassword"> </span>
        </div>
        @* Buttons *@
        <div class="col col-md-12 animate-up delay-8">
            <input class="btn btn-secondary" type="submit" asp-page-handler="Cancel" value="CANCEL" />
            <input class="btn btn-primary" type="submit" asp-page-handler="Submit" value="REGISTER" />
        </div>
        @* Message *@
        <div class="col col-md-12">
            <p class="lead">
                @Model.StatusMessage
            </p>
        </div>
        <div class="col col-md-12 animate-fade delay-9">
            <span>Already have an account? </span><a asp-page="/Login">Login here!</a>
        </div>
    </div>
</form>

@* Add section scripts for client-side validation so that invalid data does not get sent to the server *@
@section Scripts {
    @{
        @* This references Javascript files needed for validation. Located in the shared folder*@
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }